-- Applied as migration: add_admin_player_grant_queue

create table if not exists public.game_admin_player_grants (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  resource text not null,
  amount numeric not null,
  created_at timestamptz not null default now(),
  claimed_at timestamptz,
  claimed_by uuid references auth.users(id) on delete set null,
  constraint game_admin_player_grants_amount check (amount > 0),
  constraint game_admin_player_grants_resource check (
    resource = any (array['clicks','bank_clicks','gems','auto_clickers','click_upgrades','rebirths','rebirth_gem_levels','overclock_levels','auto_accelerator_levels','click_overdrive_levels','gem_station_levels','upgrade_discount_levels'])
  )
);

create index if not exists game_admin_player_grants_target_idx
  on public.game_admin_player_grants (target_user_id, created_at);

alter table public.game_admin_player_grants enable row level security;

create policy "Players can view their own admin grants"
on public.game_admin_player_grants
for select to authenticated
using (auth.uid() = target_user_id);

create or replace function public.claim_game_admin_player_grants(limit_count integer default 100)
returns table (id bigint, resource text, amount numeric, created_at timestamptz)
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  return query
  with claimed as (
    select g.id from public.game_admin_player_grants g
    where g.target_user_id = auth.uid()
      and (g.claimed_at is null or g.claimed_at < now() - interval '10 minutes')
    order by g.created_at
    limit greatest(1, least(coalesce(limit_count, 100), 100))
    for update skip locked
  )
  update public.game_admin_player_grants g
  set claimed_at = now(), claimed_by = auth.uid()
  from claimed where g.id = claimed.id
  returning g.id, g.resource, g.amount, g.created_at;
end;
$$;

create or replace function public.complete_game_admin_player_grants(grant_ids bigint[])
returns integer language plpgsql security definer set search_path = public
as $$
declare deleted_count integer;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  delete from public.game_admin_player_grants where id = any(grant_ids) and claimed_by = auth.uid();
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create or replace function public.release_game_admin_player_grants(grant_ids bigint[])
returns integer language plpgsql security definer set search_path = public
as $$
declare released_count integer;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  update public.game_admin_player_grants set claimed_at = null, claimed_by = null
  where id = any(grant_ids) and claimed_by = auth.uid();
  get diagnostics released_count = row_count;
  return released_count;
end;
$$;

revoke all on public.game_admin_player_grants from anon, authenticated;
grant select on public.game_admin_player_grants to authenticated;
grant execute on function public.claim_game_admin_player_grants(integer) to authenticated;
grant execute on function public.complete_game_admin_player_grants(bigint[]) to authenticated;
grant execute on function public.release_game_admin_player_grants(bigint[]);