-- Applied to Supabase project itriqucjgayokvddrbxm
-- Migration name: add_game_direct_messages
-- Purpose: private 1-to-1 messages for the existing game Chat panel.

create table public.game_direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  sender_username text not null,
  message text not null,
  created_at timestamptz not null default now(),
  constraint game_direct_messages_message_length check (char_length(message) between 1 and 300),
  constraint game_direct_messages_sender_username_length check (char_length(sender_username) between 3 and 20)
);

alter table public.game_direct_messages enable row level security;

revoke all on table public.game_direct_messages from anon, authenticated;
grant select, insert on table public.game_direct_messages to authenticated;
grant all on table public.game_direct_messages to service_role;
grant usage, select on sequence public.game_direct_messages_id_seq to authenticated, service_role;

create index game_direct_messages_sender_recipient_created_idx
  on public.game_direct_messages (sender_id, recipient_id, created_at desc);

create index game_direct_messages_recipient_sender_created_idx
  on public.game_direct_messages (recipient_id, sender_id, created_at desc);

create policy "Users can read their own direct messages"
  on public.game_direct_messages
  for select
  to authenticated
  using (
    (select auth.uid()) = sender_id
    or
    (select auth.uid()) = recipient_id
  );

create policy "Users can send direct messages as themselves"
  on public.game_direct_messages
  for insert
  to authenticated
  with check (
    (select auth.uid()) = sender_id
    and
    sender_username = coalesce(
      (select gp.username from public.game_profiles gp where gp.user_id = (select auth.uid())),
      ''
    )
  );

alter publication supabase_realtime add table public.game_direct_messages;
